default_agent: ai_solutions_squad_doc_agent
agents:
  ai_solutions_squad_doc_agent:
    name: ai_solutions_squad_doc_agent
    entrypoint: ai_solutions_squad_doc_agent.py
    platform: linux/arm64
    container_runtime: none
    aws:
      execution_role: arn:aws:iam::582821021539:role/AmazonBedrockAgentCoreRuntime
      execution_role_auto_create: true
      account: '582821021539'
      region: us-east-1
      ecr_repository: 582821021539.dkr.ecr.us-east-1.amazonaws.com/bedrock-agentcore-ai_solutions_squad_doc_agent
      ecr_auto_create: false
      network_configuration:
        network_mode: PUBLIC
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
    bedrock_agentcore:
      agent_id: ai_solutions_squad_doc_agent-HCjU6uHqZu
      agent_arn: arn:aws:bedrock-agentcore:us-east-1:582821021539:runtime/ai_solutions_squad_doc_agent-HCjU6uHqZu
      agent_session_id: 5366f2b5-d146-4866-acd6-053f7d8e1c7d
    codebuild:
      project_name: bedrock-agentcore-ai_solutions_squad_doc_agent-builder
      execution_role: arn:aws:iam::582821021539:role/AmazonBedrockAgentCoreSDKCodeBuild-us-east-1-292fa7b4f9
      source_bucket: bedrock-agentcore-codebuild-sources-582821021539-us-east-1
    authorizer_configuration: null
    oauth_configuration: null
